export const TEMPLATES = [
  {
    id: "kick-off",
    phase: "01 Oriëntatie",
    title: "Kick-off",
    body: "Agenda, rollen, resultaat/uitkomst/doel en afspraken voor het startoverleg.",
    href: "/templates/kick-off.doc",
    file: "kick-off.doc",
    kind: "Word",
  },
  {
    id: "wbs",
    phase: "02 Voorbereiding",
    title: "WBS",
    body: "Hiërarchie van werkpakketten: resultaat, eigenaar, inspanning en status.",
    href: "/templates/wbs.xls",
    file: "wbs.xls",
    kind: "Excel",
  },
  {
    id: "planning",
    phase: "03 Definitie",
    title: "Projectplanning",
    body: "Activiteiten en mijlpalen met start, einde, voorganger en status.",
    href: "/templates/projectplanning.xls",
    file: "projectplanning.xls",
    kind: "Excel",
  },
  {
    id: "gantt",
    phase: "03 Definitie",
    title: "Gantt",
    body: "Zestien weken met balken en mijlpalen. Wijzig de startdatum in de kop en kopieer de blauwe cellen over de weken van de activiteit.",
    href: "/templates/gantt.xls",
    file: "gantt.xls",
    kind: "Excel",
  },
  {
    id: "weekstatus",
    phase: "04 Uitvoering",
    title: "Weekstatus",
    body: "Kop voor de weekstart: voortgang, toprisico’s, gevraagde besluiten.",
    href: "/templates/weekstatus.doc",
    file: "weekstatus.doc",
    kind: "Word",
  },
  {
    id: "beslispunt",
    phase: "05 Afsluiting / poort",
    title: "Beslispunt",
    body: "Ga, nader uitwerken of stoppen. Baseline, risico’s en besluitregel.",
    href: "/templates/beslispunt.doc",
    file: "beslispunt.doc",
    kind: "Word",
  },
] as const;
