export const TEMPLATES = [
  {
    id: "kick-off",
    phase: "01 Oriëntatie",
    title: "Kick-off",
    body: "Word-bestand, gevuld met naam, opdrachtgever, resultaat, uitkomst, doel en scope.",
    href: "/templates/kick-off.doc",
    file: "kick-off.doc",
    kind: "Word",
  },
  {
    id: "wbs",
    phase: "02 Voorbereiding",
    title: "WBS",
    body: "Excel vanuit de Gantt-regels: WBS, eigenaar, start, einde en duur.",
    href: "/templates/wbs.xls",
    file: "wbs.xls",
    kind: "Excel",
  },
  {
    id: "planning",
    phase: "03 Definitie",
    title: "Projectplanning",
    body: "Excel-lijst van dezelfde activiteiten als in de Gantt, met berekende duur.",
    href: "/templates/projectplanning.xls",
    file: "projectplanning.xls",
    kind: "Excel",
  },
  {
    id: "gantt",
    phase: "03 Definitie",
    title: "Gantt",
    body: "Balken volgen start en einde uit de Gantt hierboven. Download opnieuw na een wijziging.",
    href: "/templates/gantt.xls",
    file: "gantt.xls",
    kind: "Excel",
  },
  {
    id: "msproject",
    phase: "03 Definitie",
    title: "Microsoft Project",
    body: "XML die Project opent (Bestand → Openen). Taken, datums en mijlpalen komen uit de Gantt. Geen echt .mpp: dat formaat is gesloten.",
    href: "/templates/planning.xml",
    file: "planning.xml",
    kind: "Project",
  },
  {
    id: "weekstatus",
    phase: "04 Uitvoering",
    title: "Weekstatus",
    body: "Word-status: stand, budget, toprisico’s en open issues uit de registers.",
    href: "/templates/weekstatus.doc",
    file: "weekstatus.doc",
    kind: "Word",
  },
  {
    id: "beslispunt",
    phase: "05 Afsluiting / poort",
    title: "Beslispunt",
    body: "Word-poortbrief uit de huidige stand, klaar om een besluit op te zetten.",
    href: "/templates/beslispunt.doc",
    file: "beslispunt.doc",
    kind: "Word",
  },
] as const;
