export const TEMPLATES = [
  {
    id: "kick-off",
    phase: "01 Oriëntatie",
    phaseEn: "01 Framing",
    title: "Kick-off",
    titleEn: "Kick-off",
    body: "Word-bestand, gevuld met naam, opdrachtgever, resultaat, uitkomst, doel en scope.",
    bodyEn: "Word file, filled with name, sponsor, result, outcome, goal and scope.",
    href: "/templates/kick-off.doc",
    file: "kick-off.doc",
    kind: "Word",
  },
  {
    id: "wbs",
    phase: "02 Voorbereiding",
    phaseEn: "02 Preparation",
    title: "WBS",
    titleEn: "WBS",
    body: "Excel vanuit de Gantt-regels: WBS, eigenaar, start, einde en duur.",
    bodyEn: "Excel from the Gantt rows: WBS, owner, start, end and duration.",
    href: "/templates/wbs.xls",
    file: "wbs.xls",
    kind: "Excel",
  },
  {
    id: "planning",
    phase: "03 Definitie",
    phaseEn: "03 Definition",
    title: "Projectplanning",
    titleEn: "Project schedule",
    body: "Excel-lijst van dezelfde activiteiten als in de Gantt, met berekende duur.",
    bodyEn: "Excel list of the same activities as in the Gantt, with calculated duration.",
    href: "/templates/projectplanning.xls",
    file: "projectplanning.xls",
    kind: "Excel",
  },
  {
    id: "gantt",
    phase: "03 Definitie",
    phaseEn: "03 Definition",
    title: "Gantt",
    titleEn: "Gantt",
    body: "Balken volgen start en einde uit de Gantt hierboven. Download opnieuw na een wijziging.",
    bodyEn: "Bars follow the start and end from the Gantt above. Download again after a change.",
    href: "/templates/gantt.xls",
    file: "gantt.xls",
    kind: "Excel",
  },
  {
    id: "msproject",
    phase: "03 Definitie",
    phaseEn: "03 Definition",
    title: "Microsoft Project",
    titleEn: "Microsoft Project",
    body: "XML die Project opent (Bestand → Openen). Taken, datums en mijlpalen komen uit de Gantt. Geen echt .mpp: dat formaat is gesloten.",
    bodyEn: "XML that Project opens (File → Open). Tasks, dates and milestones come from the Gantt. Not a real .mpp: that format is closed.",
    href: "/templates/planning.xml",
    file: "planning.xml",
    kind: "Project",
  },
  {
    id: "weekstatus",
    phase: "04 Uitvoering",
    phaseEn: "04 Delivery",
    title: "Weekstatus",
    titleEn: "Week status",
    body: "Word-status: stand, budget, toprisico’s en open issues uit de registers.",
    bodyEn: "Word status: status, budget, top risks and open issues from the registers.",
    href: "/templates/weekstatus.doc",
    file: "weekstatus.doc",
    kind: "Word",
  },
  {
    id: "beslispunt",
    phase: "05 Afsluiting / poort",
    phaseEn: "05 Close-out / gate",
    title: "Beslispunt",
    titleEn: "Gate",
    body: "Word-poortbrief uit de huidige stand, klaar om een besluit op te zetten.",
    bodyEn: "Word gate letter from the current status, ready to record a decision.",
    href: "/templates/beslispunt.doc",
    file: "beslispunt.doc",
    kind: "Word",
  },
] as const;
