/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OverMijRouteImport } from './routes/over-mij'
import { Route as SpelRouteImport } from './routes/spel'
import { Route as DenkIndexRouteImport } from './routes/denk/index'
import { Route as DenkBlogRouteImport } from './routes/denk/blog'
import { Route as DenkProjectRouteImport } from './routes/denk/project'
import { Route as DoeIndexRouteImport } from './routes/doe/index'
import { Route as DoeMarathonRouteImport } from './routes/doe/marathon'
import { Route as DoeProjectenRouteImport } from './routes/doe/projecten'
import { Route as WeetIndexRouteImport } from './routes/weet/index'
import { Route as WeetSplatRouteImport } from './routes/weet/$'
import { Route as DenkToolkitIndexRouteImport } from './routes/denk/toolkit/index'
import { Route as DenkToolkitBevestigersRouteImport } from './routes/denk/toolkit/bevestigers'
import { Route as DenkToolkitBronnenRouteImport } from './routes/denk/toolkit/bronnen'
import { Route as DenkToolkitLagerpassingenRouteImport } from './routes/denk/toolkit/lagerpassingen'
import { Route as DenkToolkitORinggroefRouteImport } from './routes/denk/toolkit/o-ringgroef'
import { Route as DenkToolkitPassingenRouteImport } from './routes/denk/toolkit/passingen'
import { Route as DenkToolkitSeegerringGroefRouteImport } from './routes/denk/toolkit/seegerring-groef'
import { Route as DenkToolkitSpiebaanTolerantiesRouteImport } from './routes/denk/toolkit/spiebaan-toleranties'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverMijRoute = OverMijRouteImport.update({
  id: '/over-mij',
  path: '/over-mij',
  getParentRoute: () => rootRouteImport,
} as any)
const SpelRoute = SpelRouteImport.update({
  id: '/spel',
  path: '/spel',
  getParentRoute: () => rootRouteImport,
} as any)
const DenkIndexRoute = DenkIndexRouteImport.update({
  id: '/denk/',
  path: '/denk/',
  getParentRoute: () => rootRouteImport,
} as any)
const DenkBlogRoute = DenkBlogRouteImport.update({
  id: '/denk/blog',
  path: '/denk/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const DenkProjectRoute = DenkProjectRouteImport.update({
  id: '/denk/project',
  path: '/denk/project',
  getParentRoute: () => rootRouteImport,
} as any)
const DoeIndexRoute = DoeIndexRouteImport.update({
  id: '/doe/',
  path: '/doe/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoeMarathonRoute = DoeMarathonRouteImport.update({
  id: '/doe/marathon',
  path: '/doe/marathon',
  getParentRoute: () => rootRouteImport,
} as any)
const DoeProjectenRoute = DoeProjectenRouteImport.update({
  id: '/doe/projecten',
  path: '/doe/projecten',
  getParentRoute: () => rootRouteImport,
} as any)
const WeetIndexRoute = WeetIndexRouteImport.update({
  id: '/weet/',
  path: '/weet/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeetSplatRoute = WeetSplatRouteImport.update({
  id: '/weet/$',
  path: '/weet/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DenkToolkitIndexRoute = DenkToolkitIndexRouteImport.update({
  id: '/denk/toolkit/',
  path: '/denk/toolkit/',
  getParentRoute: () => rootRouteImport,
} as any)
const DenkToolkitBevestigersRoute = DenkToolkitBevestigersRouteImport.update({
  id: '/denk/toolkit/bevestigers',
  path: '/denk/toolkit/bevestigers',
  getParentRoute: () => rootRouteImport,
} as any)
const DenkToolkitBronnenRoute = DenkToolkitBronnenRouteImport.update({
  id: '/denk/toolkit/bronnen',
  path: '/denk/toolkit/bronnen',
  getParentRoute: () => rootRouteImport,
} as any)
const DenkToolkitLagerpassingenRoute =
  DenkToolkitLagerpassingenRouteImport.update({
    id: '/denk/toolkit/lagerpassingen',
    path: '/denk/toolkit/lagerpassingen',
    getParentRoute: () => rootRouteImport,
  } as any)
const DenkToolkitORinggroefRoute = DenkToolkitORinggroefRouteImport.update({
  id: '/denk/toolkit/o-ringgroef',
  path: '/denk/toolkit/o-ringgroef',
  getParentRoute: () => rootRouteImport,
} as any)
const DenkToolkitPassingenRoute = DenkToolkitPassingenRouteImport.update({
  id: '/denk/toolkit/passingen',
  path: '/denk/toolkit/passingen',
  getParentRoute: () => rootRouteImport,
} as any)
const DenkToolkitSeegerringGroefRoute =
  DenkToolkitSeegerringGroefRouteImport.update({
    id: '/denk/toolkit/seegerring-groef',
    path: '/denk/toolkit/seegerring-groef',
    getParentRoute: () => rootRouteImport,
  } as any)
const DenkToolkitSpiebaanTolerantiesRoute =
  DenkToolkitSpiebaanTolerantiesRouteImport.update({
    id: '/denk/toolkit/spiebaan-toleranties',
    path: '/denk/toolkit/spiebaan-toleranties',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/over-mij': typeof OverMijRoute
  '/spel': typeof SpelRoute
  '/denk/blog': typeof DenkBlogRoute
  '/denk/project': typeof DenkProjectRoute
  '/doe/marathon': typeof DoeMarathonRoute
  '/doe/projecten': typeof DoeProjectenRoute
  '/weet/$': typeof WeetSplatRoute
  '/denk/': typeof DenkIndexRoute
  '/doe/': typeof DoeIndexRoute
  '/weet/': typeof WeetIndexRoute
  '/denk/toolkit/bevestigers': typeof DenkToolkitBevestigersRoute
  '/denk/toolkit/bronnen': typeof DenkToolkitBronnenRoute
  '/denk/toolkit/lagerpassingen': typeof DenkToolkitLagerpassingenRoute
  '/denk/toolkit/o-ringgroef': typeof DenkToolkitORinggroefRoute
  '/denk/toolkit/passingen': typeof DenkToolkitPassingenRoute
  '/denk/toolkit/seegerring-groef': typeof DenkToolkitSeegerringGroefRoute
  '/denk/toolkit/spiebaan-toleranties': typeof DenkToolkitSpiebaanTolerantiesRoute
  '/denk/toolkit/': typeof DenkToolkitIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/over-mij': typeof OverMijRoute
  '/spel': typeof SpelRoute
  '/denk/blog': typeof DenkBlogRoute
  '/denk/project': typeof DenkProjectRoute
  '/doe/marathon': typeof DoeMarathonRoute
  '/doe/projecten': typeof DoeProjectenRoute
  '/weet/$': typeof WeetSplatRoute
  '/denk': typeof DenkIndexRoute
  '/doe': typeof DoeIndexRoute
  '/weet': typeof WeetIndexRoute
  '/denk/toolkit/bevestigers': typeof DenkToolkitBevestigersRoute
  '/denk/toolkit/bronnen': typeof DenkToolkitBronnenRoute
  '/denk/toolkit/lagerpassingen': typeof DenkToolkitLagerpassingenRoute
  '/denk/toolkit/o-ringgroef': typeof DenkToolkitORinggroefRoute
  '/denk/toolkit/passingen': typeof DenkToolkitPassingenRoute
  '/denk/toolkit/seegerring-groef': typeof DenkToolkitSeegerringGroefRoute
  '/denk/toolkit/spiebaan-toleranties': typeof DenkToolkitSpiebaanTolerantiesRoute
  '/denk/toolkit': typeof DenkToolkitIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/over-mij': typeof OverMijRoute
  '/spel': typeof SpelRoute
  '/denk/blog': typeof DenkBlogRoute
  '/denk/project': typeof DenkProjectRoute
  '/doe/marathon': typeof DoeMarathonRoute
  '/doe/projecten': typeof DoeProjectenRoute
  '/weet/$': typeof WeetSplatRoute
  '/denk/': typeof DenkIndexRoute
  '/doe/': typeof DoeIndexRoute
  '/weet/': typeof WeetIndexRoute
  '/denk/toolkit/bevestigers': typeof DenkToolkitBevestigersRoute
  '/denk/toolkit/bronnen': typeof DenkToolkitBronnenRoute
  '/denk/toolkit/lagerpassingen': typeof DenkToolkitLagerpassingenRoute
  '/denk/toolkit/o-ringgroef': typeof DenkToolkitORinggroefRoute
  '/denk/toolkit/passingen': typeof DenkToolkitPassingenRoute
  '/denk/toolkit/seegerring-groef': typeof DenkToolkitSeegerringGroefRoute
  '/denk/toolkit/spiebaan-toleranties': typeof DenkToolkitSpiebaanTolerantiesRoute
  '/denk/toolkit/': typeof DenkToolkitIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/over-mij'
    | '/spel'
    | '/denk/blog'
    | '/denk/project'
    | '/doe/marathon'
    | '/doe/projecten'
    | '/weet/$'
    | '/denk/'
    | '/doe/'
    | '/weet/'
    | '/denk/toolkit/bevestigers'
    | '/denk/toolkit/bronnen'
    | '/denk/toolkit/lagerpassingen'
    | '/denk/toolkit/o-ringgroef'
    | '/denk/toolkit/passingen'
    | '/denk/toolkit/seegerring-groef'
    | '/denk/toolkit/spiebaan-toleranties'
    | '/denk/toolkit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/over-mij'
    | '/spel'
    | '/denk/blog'
    | '/denk/project'
    | '/doe/marathon'
    | '/doe/projecten'
    | '/weet/$'
    | '/denk'
    | '/doe'
    | '/weet'
    | '/denk/toolkit/bevestigers'
    | '/denk/toolkit/bronnen'
    | '/denk/toolkit/lagerpassingen'
    | '/denk/toolkit/o-ringgroef'
    | '/denk/toolkit/passingen'
    | '/denk/toolkit/seegerring-groef'
    | '/denk/toolkit/spiebaan-toleranties'
    | '/denk/toolkit'
  id:
    | '__root__'
    | '/'
    | '/over-mij'
    | '/spel'
    | '/denk/blog'
    | '/denk/project'
    | '/doe/marathon'
    | '/doe/projecten'
    | '/weet/$'
    | '/denk/'
    | '/doe/'
    | '/weet/'
    | '/denk/toolkit/bevestigers'
    | '/denk/toolkit/bronnen'
    | '/denk/toolkit/lagerpassingen'
    | '/denk/toolkit/o-ringgroef'
    | '/denk/toolkit/passingen'
    | '/denk/toolkit/seegerring-groef'
    | '/denk/toolkit/spiebaan-toleranties'
    | '/denk/toolkit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OverMijRoute: typeof OverMijRoute
  SpelRoute: typeof SpelRoute
  DenkBlogRoute: typeof DenkBlogRoute
  DenkProjectRoute: typeof DenkProjectRoute
  DoeMarathonRoute: typeof DoeMarathonRoute
  DoeProjectenRoute: typeof DoeProjectenRoute
  WeetSplatRoute: typeof WeetSplatRoute
  DenkIndexRoute: typeof DenkIndexRoute
  DoeIndexRoute: typeof DoeIndexRoute
  WeetIndexRoute: typeof WeetIndexRoute
  DenkToolkitBevestigersRoute: typeof DenkToolkitBevestigersRoute
  DenkToolkitBronnenRoute: typeof DenkToolkitBronnenRoute
  DenkToolkitLagerpassingenRoute: typeof DenkToolkitLagerpassingenRoute
  DenkToolkitORinggroefRoute: typeof DenkToolkitORinggroefRoute
  DenkToolkitPassingenRoute: typeof DenkToolkitPassingenRoute
  DenkToolkitSeegerringGroefRoute: typeof DenkToolkitSeegerringGroefRoute
  DenkToolkitSpiebaanTolerantiesRoute: typeof DenkToolkitSpiebaanTolerantiesRoute
  DenkToolkitIndexRoute: typeof DenkToolkitIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-mij': {
      id: '/over-mij'
      path: '/over-mij'
      fullPath: '/over-mij'
      preLoaderRoute: typeof OverMijRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spel': {
      id: '/spel'
      path: '/spel'
      fullPath: '/spel'
      preLoaderRoute: typeof SpelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denk/': {
      id: '/denk/'
      path: '/denk'
      fullPath: '/denk/'
      preLoaderRoute: typeof DenkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denk/blog': {
      id: '/denk/blog'
      path: '/denk/blog'
      fullPath: '/denk/blog'
      preLoaderRoute: typeof DenkBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denk/project': {
      id: '/denk/project'
      path: '/denk/project'
      fullPath: '/denk/project'
      preLoaderRoute: typeof DenkProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doe/': {
      id: '/doe/'
      path: '/doe'
      fullPath: '/doe/'
      preLoaderRoute: typeof DoeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doe/marathon': {
      id: '/doe/marathon'
      path: '/doe/marathon'
      fullPath: '/doe/marathon'
      preLoaderRoute: typeof DoeMarathonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doe/projecten': {
      id: '/doe/projecten'
      path: '/doe/projecten'
      fullPath: '/doe/projecten'
      preLoaderRoute: typeof DoeProjectenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weet/': {
      id: '/weet/'
      path: '/weet'
      fullPath: '/weet/'
      preLoaderRoute: typeof WeetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weet/$': {
      id: '/weet/$'
      path: '/weet/$'
      fullPath: '/weet/$'
      preLoaderRoute: typeof WeetSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denk/toolkit/': {
      id: '/denk/toolkit/'
      path: '/denk/toolkit'
      fullPath: '/denk/toolkit/'
      preLoaderRoute: typeof DenkToolkitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denk/toolkit/bevestigers': {
      id: '/denk/toolkit/bevestigers'
      path: '/denk/toolkit/bevestigers'
      fullPath: '/denk/toolkit/bevestigers'
      preLoaderRoute: typeof DenkToolkitBevestigersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denk/toolkit/bronnen': {
      id: '/denk/toolkit/bronnen'
      path: '/denk/toolkit/bronnen'
      fullPath: '/denk/toolkit/bronnen'
      preLoaderRoute: typeof DenkToolkitBronnenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denk/toolkit/lagerpassingen': {
      id: '/denk/toolkit/lagerpassingen'
      path: '/denk/toolkit/lagerpassingen'
      fullPath: '/denk/toolkit/lagerpassingen'
      preLoaderRoute: typeof DenkToolkitLagerpassingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denk/toolkit/o-ringgroef': {
      id: '/denk/toolkit/o-ringgroef'
      path: '/denk/toolkit/o-ringgroef'
      fullPath: '/denk/toolkit/o-ringgroef'
      preLoaderRoute: typeof DenkToolkitORinggroefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denk/toolkit/passingen': {
      id: '/denk/toolkit/passingen'
      path: '/denk/toolkit/passingen'
      fullPath: '/denk/toolkit/passingen'
      preLoaderRoute: typeof DenkToolkitPassingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denk/toolkit/seegerring-groef': {
      id: '/denk/toolkit/seegerring-groef'
      path: '/denk/toolkit/seegerring-groef'
      fullPath: '/denk/toolkit/seegerring-groef'
      preLoaderRoute: typeof DenkToolkitSeegerringGroefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denk/toolkit/spiebaan-toleranties': {
      id: '/denk/toolkit/spiebaan-toleranties'
      path: '/denk/toolkit/spiebaan-toleranties'
      fullPath: '/denk/toolkit/spiebaan-toleranties'
      preLoaderRoute: typeof DenkToolkitSpiebaanTolerantiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OverMijRoute: OverMijRoute,
  SpelRoute: SpelRoute,
  DenkBlogRoute: DenkBlogRoute,
  DenkProjectRoute: DenkProjectRoute,
  DoeMarathonRoute: DoeMarathonRoute,
  DoeProjectenRoute: DoeProjectenRoute,
  WeetSplatRoute: WeetSplatRoute,
  DenkIndexRoute: DenkIndexRoute,
  DoeIndexRoute: DoeIndexRoute,
  WeetIndexRoute: WeetIndexRoute,
  DenkToolkitBevestigersRoute: DenkToolkitBevestigersRoute,
  DenkToolkitBronnenRoute: DenkToolkitBronnenRoute,
  DenkToolkitLagerpassingenRoute: DenkToolkitLagerpassingenRoute,
  DenkToolkitORinggroefRoute: DenkToolkitORinggroefRoute,
  DenkToolkitPassingenRoute: DenkToolkitPassingenRoute,
  DenkToolkitSeegerringGroefRoute: DenkToolkitSeegerringGroefRoute,
  DenkToolkitSpiebaanTolerantiesRoute: DenkToolkitSpiebaanTolerantiesRoute,
  DenkToolkitIndexRoute: DenkToolkitIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
