/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MarathonRouteImport } from './routes/marathon'
import { Route as OverMijRouteImport } from './routes/over-mij'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as ProjectRouteImport } from './routes/project'
import { Route as ProjectenRouteImport } from './routes/projecten'
import { Route as SpelRouteImport } from './routes/spel'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogUsbCLabtafelMhsRouteImport } from './routes/blog/usb-c-labtafel-mhs'
import { Route as ToolkitIndexRouteImport } from './routes/toolkit/index'
import { Route as ToolkitBevestigersRouteImport } from './routes/toolkit/bevestigers'
import { Route as ToolkitBronnenRouteImport } from './routes/toolkit/bronnen'
import { Route as ToolkitCilinderRouteImport } from './routes/toolkit/cilinder'
import { Route as ToolkitEenhedenRouteImport } from './routes/toolkit/eenheden'
import { Route as ToolkitIso2768RouteImport } from './routes/toolkit/iso-2768'
import { Route as ToolkitKantenRouteImport } from './routes/toolkit/kanten'
import { Route as ToolkitKnikberekeningRouteImport } from './routes/toolkit/knikberekening'
import { Route as ToolkitLagerpassingenRouteImport } from './routes/toolkit/lagerpassingen'
import { Route as ToolkitMacrosRouteImport } from './routes/toolkit/macros'
import { Route as ToolkitMotorspecificatieRouteImport } from './routes/toolkit/motorspecificatie'
import { Route as ToolkitORinggroefRouteImport } from './routes/toolkit/o-ringgroef'
import { Route as ToolkitPassingenRouteImport } from './routes/toolkit/passingen'
import { Route as ToolkitSeegerringGroefRouteImport } from './routes/toolkit/seegerring-groef'
import { Route as ToolkitSpiebaanTolerantiesRouteImport } from './routes/toolkit/spiebaan-toleranties'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MarathonRoute = MarathonRouteImport.update({
  id: '/marathon',
  path: '/marathon',
  getParentRoute: () => rootRouteImport,
} as any)
const OverMijRoute = OverMijRouteImport.update({
  id: '/over-mij',
  path: '/over-mij',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRoute = ProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectenRoute = ProjectenRouteImport.update({
  id: '/projecten',
  path: '/projecten',
  getParentRoute: () => rootRouteImport,
} as any)
const SpelRoute = SpelRouteImport.update({
  id: '/spel',
  path: '/spel',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogUsbCLabtafelMhsRoute = BlogUsbCLabtafelMhsRouteImport.update({
  id: '/blog/usb-c-labtafel-mhs',
  path: '/blog/usb-c-labtafel-mhs',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitIndexRoute = ToolkitIndexRouteImport.update({
  id: '/toolkit/',
  path: '/toolkit/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitBevestigersRoute = ToolkitBevestigersRouteImport.update({
  id: '/toolkit/bevestigers',
  path: '/toolkit/bevestigers',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitBronnenRoute = ToolkitBronnenRouteImport.update({
  id: '/toolkit/bronnen',
  path: '/toolkit/bronnen',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitCilinderRoute = ToolkitCilinderRouteImport.update({
  id: '/toolkit/cilinder',
  path: '/toolkit/cilinder',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitEenhedenRoute = ToolkitEenhedenRouteImport.update({
  id: '/toolkit/eenheden',
  path: '/toolkit/eenheden',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitIso2768Route = ToolkitIso2768RouteImport.update({
  id: '/toolkit/iso-2768',
  path: '/toolkit/iso-2768',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitKantenRoute = ToolkitKantenRouteImport.update({
  id: '/toolkit/kanten',
  path: '/toolkit/kanten',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitKnikberekeningRoute = ToolkitKnikberekeningRouteImport.update({
  id: '/toolkit/knikberekening',
  path: '/toolkit/knikberekening',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitLagerpassingenRoute = ToolkitLagerpassingenRouteImport.update({
  id: '/toolkit/lagerpassingen',
  path: '/toolkit/lagerpassingen',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitMacrosRoute = ToolkitMacrosRouteImport.update({
  id: '/toolkit/macros',
  path: '/toolkit/macros',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitMotorspecificatieRoute =
  ToolkitMotorspecificatieRouteImport.update({
    id: '/toolkit/motorspecificatie',
    path: '/toolkit/motorspecificatie',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolkitORinggroefRoute = ToolkitORinggroefRouteImport.update({
  id: '/toolkit/o-ringgroef',
  path: '/toolkit/o-ringgroef',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitPassingenRoute = ToolkitPassingenRouteImport.update({
  id: '/toolkit/passingen',
  path: '/toolkit/passingen',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitSeegerringGroefRoute = ToolkitSeegerringGroefRouteImport.update({
  id: '/toolkit/seegerring-groef',
  path: '/toolkit/seegerring-groef',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitSpiebaanTolerantiesRoute =
  ToolkitSpiebaanTolerantiesRouteImport.update({
    id: '/toolkit/spiebaan-toleranties',
    path: '/toolkit/spiebaan-toleranties',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/marathon': typeof MarathonRoute
  '/over-mij': typeof OverMijRoute
  '/podcast': typeof PodcastRoute
  '/project': typeof ProjectRoute
  '/projecten': typeof ProjectenRoute
  '/spel': typeof SpelRoute
  '/blog/usb-c-labtafel-mhs': typeof BlogUsbCLabtafelMhsRoute
  '/toolkit/bevestigers': typeof ToolkitBevestigersRoute
  '/toolkit/bronnen': typeof ToolkitBronnenRoute
  '/toolkit/cilinder': typeof ToolkitCilinderRoute
  '/toolkit/eenheden': typeof ToolkitEenhedenRoute
  '/toolkit/iso-2768': typeof ToolkitIso2768Route
  '/toolkit/kanten': typeof ToolkitKantenRoute
  '/toolkit/knikberekening': typeof ToolkitKnikberekeningRoute
  '/toolkit/lagerpassingen': typeof ToolkitLagerpassingenRoute
  '/toolkit/macros': typeof ToolkitMacrosRoute
  '/toolkit/motorspecificatie': typeof ToolkitMotorspecificatieRoute
  '/toolkit/o-ringgroef': typeof ToolkitORinggroefRoute
  '/toolkit/passingen': typeof ToolkitPassingenRoute
  '/toolkit/seegerring-groef': typeof ToolkitSeegerringGroefRoute
  '/toolkit/spiebaan-toleranties': typeof ToolkitSpiebaanTolerantiesRoute
  '/blog/': typeof BlogIndexRoute
  '/toolkit/': typeof ToolkitIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/marathon': typeof MarathonRoute
  '/over-mij': typeof OverMijRoute
  '/podcast': typeof PodcastRoute
  '/project': typeof ProjectRoute
  '/projecten': typeof ProjectenRoute
  '/spel': typeof SpelRoute
  '/blog/usb-c-labtafel-mhs': typeof BlogUsbCLabtafelMhsRoute
  '/toolkit/bevestigers': typeof ToolkitBevestigersRoute
  '/toolkit/bronnen': typeof ToolkitBronnenRoute
  '/toolkit/cilinder': typeof ToolkitCilinderRoute
  '/toolkit/eenheden': typeof ToolkitEenhedenRoute
  '/toolkit/iso-2768': typeof ToolkitIso2768Route
  '/toolkit/kanten': typeof ToolkitKantenRoute
  '/toolkit/knikberekening': typeof ToolkitKnikberekeningRoute
  '/toolkit/lagerpassingen': typeof ToolkitLagerpassingenRoute
  '/toolkit/macros': typeof ToolkitMacrosRoute
  '/toolkit/motorspecificatie': typeof ToolkitMotorspecificatieRoute
  '/toolkit/o-ringgroef': typeof ToolkitORinggroefRoute
  '/toolkit/passingen': typeof ToolkitPassingenRoute
  '/toolkit/seegerring-groef': typeof ToolkitSeegerringGroefRoute
  '/toolkit/spiebaan-toleranties': typeof ToolkitSpiebaanTolerantiesRoute
  '/blog': typeof BlogIndexRoute
  '/toolkit': typeof ToolkitIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/marathon': typeof MarathonRoute
  '/over-mij': typeof OverMijRoute
  '/podcast': typeof PodcastRoute
  '/project': typeof ProjectRoute
  '/projecten': typeof ProjectenRoute
  '/spel': typeof SpelRoute
  '/blog/usb-c-labtafel-mhs': typeof BlogUsbCLabtafelMhsRoute
  '/toolkit/bevestigers': typeof ToolkitBevestigersRoute
  '/toolkit/bronnen': typeof ToolkitBronnenRoute
  '/toolkit/cilinder': typeof ToolkitCilinderRoute
  '/toolkit/eenheden': typeof ToolkitEenhedenRoute
  '/toolkit/iso-2768': typeof ToolkitIso2768Route
  '/toolkit/kanten': typeof ToolkitKantenRoute
  '/toolkit/knikberekening': typeof ToolkitKnikberekeningRoute
  '/toolkit/lagerpassingen': typeof ToolkitLagerpassingenRoute
  '/toolkit/macros': typeof ToolkitMacrosRoute
  '/toolkit/motorspecificatie': typeof ToolkitMotorspecificatieRoute
  '/toolkit/o-ringgroef': typeof ToolkitORinggroefRoute
  '/toolkit/passingen': typeof ToolkitPassingenRoute
  '/toolkit/seegerring-groef': typeof ToolkitSeegerringGroefRoute
  '/toolkit/spiebaan-toleranties': typeof ToolkitSpiebaanTolerantiesRoute
  '/blog/': typeof BlogIndexRoute
  '/toolkit/': typeof ToolkitIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/marathon'
    | '/over-mij'
    | '/podcast'
    | '/project'
    | '/projecten'
    | '/spel'
    | '/blog/usb-c-labtafel-mhs'
    | '/toolkit/bevestigers'
    | '/toolkit/bronnen'
    | '/toolkit/cilinder'
    | '/toolkit/eenheden'
    | '/toolkit/iso-2768'
    | '/toolkit/kanten'
    | '/toolkit/knikberekening'
    | '/toolkit/lagerpassingen'
    | '/toolkit/macros'
    | '/toolkit/motorspecificatie'
    | '/toolkit/o-ringgroef'
    | '/toolkit/passingen'
    | '/toolkit/seegerring-groef'
    | '/toolkit/spiebaan-toleranties'
    | '/blog/'
    | '/toolkit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/marathon'
    | '/over-mij'
    | '/podcast'
    | '/project'
    | '/projecten'
    | '/spel'
    | '/blog/usb-c-labtafel-mhs'
    | '/toolkit/bevestigers'
    | '/toolkit/bronnen'
    | '/toolkit/cilinder'
    | '/toolkit/eenheden'
    | '/toolkit/iso-2768'
    | '/toolkit/kanten'
    | '/toolkit/knikberekening'
    | '/toolkit/lagerpassingen'
    | '/toolkit/macros'
    | '/toolkit/motorspecificatie'
    | '/toolkit/o-ringgroef'
    | '/toolkit/passingen'
    | '/toolkit/seegerring-groef'
    | '/toolkit/spiebaan-toleranties'
    | '/blog'
    | '/toolkit'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/marathon'
    | '/over-mij'
    | '/podcast'
    | '/project'
    | '/projecten'
    | '/spel'
    | '/blog/usb-c-labtafel-mhs'
    | '/toolkit/bevestigers'
    | '/toolkit/bronnen'
    | '/toolkit/cilinder'
    | '/toolkit/eenheden'
    | '/toolkit/iso-2768'
    | '/toolkit/kanten'
    | '/toolkit/knikberekening'
    | '/toolkit/lagerpassingen'
    | '/toolkit/macros'
    | '/toolkit/motorspecificatie'
    | '/toolkit/o-ringgroef'
    | '/toolkit/passingen'
    | '/toolkit/seegerring-groef'
    | '/toolkit/spiebaan-toleranties'
    | '/blog/'
    | '/toolkit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  MarathonRoute: typeof MarathonRoute
  OverMijRoute: typeof OverMijRoute
  PodcastRoute: typeof PodcastRoute
  ProjectRoute: typeof ProjectRoute
  ProjectenRoute: typeof ProjectenRoute
  SpelRoute: typeof SpelRoute
  BlogUsbCLabtafelMhsRoute: typeof BlogUsbCLabtafelMhsRoute
  ToolkitBevestigersRoute: typeof ToolkitBevestigersRoute
  ToolkitBronnenRoute: typeof ToolkitBronnenRoute
  ToolkitCilinderRoute: typeof ToolkitCilinderRoute
  ToolkitEenhedenRoute: typeof ToolkitEenhedenRoute
  ToolkitIso2768Route: typeof ToolkitIso2768Route
  ToolkitKantenRoute: typeof ToolkitKantenRoute
  ToolkitKnikberekeningRoute: typeof ToolkitKnikberekeningRoute
  ToolkitLagerpassingenRoute: typeof ToolkitLagerpassingenRoute
  ToolkitMacrosRoute: typeof ToolkitMacrosRoute
  ToolkitMotorspecificatieRoute: typeof ToolkitMotorspecificatieRoute
  ToolkitORinggroefRoute: typeof ToolkitORinggroefRoute
  ToolkitPassingenRoute: typeof ToolkitPassingenRoute
  ToolkitSeegerringGroefRoute: typeof ToolkitSeegerringGroefRoute
  ToolkitSpiebaanTolerantiesRoute: typeof ToolkitSpiebaanTolerantiesRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ToolkitIndexRoute: typeof ToolkitIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marathon': {
      id: '/marathon'
      path: '/marathon'
      fullPath: '/marathon'
      preLoaderRoute: typeof MarathonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-mij': {
      id: '/over-mij'
      path: '/over-mij'
      fullPath: '/over-mij'
      preLoaderRoute: typeof OverMijRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projecten': {
      id: '/projecten'
      path: '/projecten'
      fullPath: '/projecten'
      preLoaderRoute: typeof ProjectenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spel': {
      id: '/spel'
      path: '/spel'
      fullPath: '/spel'
      preLoaderRoute: typeof SpelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/usb-c-labtafel-mhs': {
      id: '/blog/usb-c-labtafel-mhs'
      path: '/blog/usb-c-labtafel-mhs'
      fullPath: '/blog/usb-c-labtafel-mhs'
      preLoaderRoute: typeof BlogUsbCLabtafelMhsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit/': {
      id: '/toolkit/'
      path: '/toolkit'
      fullPath: '/toolkit/'
      preLoaderRoute: typeof ToolkitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit/bevestigers': {
      id: '/toolkit/bevestigers'
      path: '/toolkit/bevestigers'
      fullPath: '/toolkit/bevestigers'
      preLoaderRoute: typeof ToolkitBevestigersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit/bronnen': {
      id: '/toolkit/bronnen'
      path: '/toolkit/bronnen'
      fullPath: '/toolkit/bronnen'
      preLoaderRoute: typeof ToolkitBronnenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit/cilinder': {
      id: '/toolkit/cilinder'
      path: '/toolkit/cilinder'
      fullPath: '/toolkit/cilinder'
      preLoaderRoute: typeof ToolkitCilinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit/eenheden': {
      id: '/toolkit/eenheden'
      path: '/toolkit/eenheden'
      fullPath: '/toolkit/eenheden'
      preLoaderRoute: typeof ToolkitEenhedenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit/iso-2768': {
      id: '/toolkit/iso-2768'
      path: '/toolkit/iso-2768'
      fullPath: '/toolkit/iso-2768'
      preLoaderRoute: typeof ToolkitIso2768RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit/kanten': {
      id: '/toolkit/kanten'
      path: '/toolkit/kanten'
      fullPath: '/toolkit/kanten'
      preLoaderRoute: typeof ToolkitKantenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit/knikberekening': {
      id: '/toolkit/knikberekening'
      path: '/toolkit/knikberekening'
      fullPath: '/toolkit/knikberekening'
      preLoaderRoute: typeof ToolkitKnikberekeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit/lagerpassingen': {
      id: '/toolkit/lagerpassingen'
      path: '/toolkit/lagerpassingen'
      fullPath: '/toolkit/lagerpassingen'
      preLoaderRoute: typeof ToolkitLagerpassingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit/macros': {
      id: '/toolkit/macros'
      path: '/toolkit/macros'
      fullPath: '/toolkit/macros'
      preLoaderRoute: typeof ToolkitMacrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit/motorspecificatie': {
      id: '/toolkit/motorspecificatie'
      path: '/toolkit/motorspecificatie'
      fullPath: '/toolkit/motorspecificatie'
      preLoaderRoute: typeof ToolkitMotorspecificatieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit/o-ringgroef': {
      id: '/toolkit/o-ringgroef'
      path: '/toolkit/o-ringgroef'
      fullPath: '/toolkit/o-ringgroef'
      preLoaderRoute: typeof ToolkitORinggroefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit/passingen': {
      id: '/toolkit/passingen'
      path: '/toolkit/passingen'
      fullPath: '/toolkit/passingen'
      preLoaderRoute: typeof ToolkitPassingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit/seegerring-groef': {
      id: '/toolkit/seegerring-groef'
      path: '/toolkit/seegerring-groef'
      fullPath: '/toolkit/seegerring-groef'
      preLoaderRoute: typeof ToolkitSeegerringGroefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit/spiebaan-toleranties': {
      id: '/toolkit/spiebaan-toleranties'
      path: '/toolkit/spiebaan-toleranties'
      fullPath: '/toolkit/spiebaan-toleranties'
      preLoaderRoute: typeof ToolkitSpiebaanTolerantiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  MarathonRoute: MarathonRoute,
  OverMijRoute: OverMijRoute,
  PodcastRoute: PodcastRoute,
  ProjectRoute: ProjectRoute,
  ProjectenRoute: ProjectenRoute,
  SpelRoute: SpelRoute,
  BlogUsbCLabtafelMhsRoute: BlogUsbCLabtafelMhsRoute,
  ToolkitBevestigersRoute: ToolkitBevestigersRoute,
  ToolkitBronnenRoute: ToolkitBronnenRoute,
  ToolkitCilinderRoute: ToolkitCilinderRoute,
  ToolkitEenhedenRoute: ToolkitEenhedenRoute,
  ToolkitIso2768Route: ToolkitIso2768Route,
  ToolkitKantenRoute: ToolkitKantenRoute,
  ToolkitKnikberekeningRoute: ToolkitKnikberekeningRoute,
  ToolkitLagerpassingenRoute: ToolkitLagerpassingenRoute,
  ToolkitMacrosRoute: ToolkitMacrosRoute,
  ToolkitMotorspecificatieRoute: ToolkitMotorspecificatieRoute,
  ToolkitORinggroefRoute: ToolkitORinggroefRoute,
  ToolkitPassingenRoute: ToolkitPassingenRoute,
  ToolkitSeegerringGroefRoute: ToolkitSeegerringGroefRoute,
  ToolkitSpiebaanTolerantiesRoute: ToolkitSpiebaanTolerantiesRoute,
  BlogIndexRoute: BlogIndexRoute,
  ToolkitIndexRoute: ToolkitIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
