/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OverMijRouteImport } from './routes/over-mij'
import { Route as SpelRouteImport } from './routes/spel'
import { Route as DenkIndexRouteImport } from './routes/denk/index'
import { Route as DenkBlogRouteImport } from './routes/denk/blog'
import { Route as DenkProjectRouteImport } from './routes/denk/project'
import { Route as DoeIndexRouteImport } from './routes/doe/index'
import { Route as DoeMarathonRouteImport } from './routes/doe/marathon'
import { Route as DoeProjectenRouteImport } from './routes/doe/projecten'
import { Route as WeetIndexRouteImport } from './routes/weet/index'
import { Route as WeetSplatRouteImport } from './routes/weet/$'
import { Route as DenkToolkitIndexRouteImport } from './routes/denk/toolkit/index'
import { Route as DenkToolkitBevestigersRouteImport } from './routes/denk/toolkit/bevestigers'
import { Route as DenkToolkitBronnenRouteImport } from './routes/denk/toolkit/bronnen'
import { Route as DenkToolkitLagerpassingenRouteImport } from './routes/denk/toolkit/lagerpassingen'
import { Route as DenkToolkitORinggroefRouteImport } from './routes/denk/toolkit/o-ringgroef'
import { Route as DenkToolkitPassingenRouteImport } from './routes/denk/toolkit/passingen'
import { Route as DenkToolkitSeegerringGroefRouteImport } from './routes/denk/toolkit/seegerring-groef'
import { Route as DenkToolkitSpiebaanTolerantiesRouteImport } from './routes/denk/toolkit/spiebaan-toleranties'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverMijRoute = OverMijRouteImport.update({
  id: '/over-mij',
  path: '/over-mij',
  getParentRoute: () => rootRouteImport,
} as any)
const SpelRoute = SpelRouteImport.update({
  id: '/spel',
  path: '/spel',
  getParentRoute: () => rootRouteImport,
} as any)
const DenkIndexRoute = DenkIndexRouteImport.update({
  id: '/denk/',
  path: '/denk/',
  getParentRoute: () => rootRouteImport,
} as any)
const DenkBlogRoute = DenkBlogRouteImport.update({
  id: '/denk/blog',
  path: '/denk/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const DenkProjectRoute = DenkProjectRouteImport.update({
  id: '/denk/project',
  path: '/denk/project',
  getParentRoute: () => rootRouteImport,
} as any)
const DoeIndexRoute = DoeIndexRouteImport.update({
  id: '/doe/',
  path: '/doe/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoeMarathonRoute = DoeMarathonRouteImport.update({
  id: '/doe/marathon',
  path: '/doe/marathon',
  getParentRoute: () => rootRouteImport,
} as any)
const DoeProjectenRoute = DoeProjectenRouteImport.update({
  id: '/doe/projecten',
  path: '/doe/projecten',
  getParentRoute: () => rootRouteImport,
} as any)
const WeetIndexRoute = WeetIndexRouteImport.update({
  id: '/weet/',
  path: '/weet/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeetSplatRoute = WeetSplatRouteImport.update({
  id: '/weet/$',
  path: '/weet/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DenkToolkitIndexRoute = DenkToolkitIndexRouteImport.update({
  id: '/denk/toolkit/',
  path: '/denk/toolkit/',
  getParentRoute: () => rootRouteImport,
} as any)
const DenkToolkitBevestigersRoute = DenkToolkitBevestigersRouteImport.update({
  id: '/denk/toolkit/bevestigers',
  path: '/denk/toolkit/bevestigers',
  getParentRoute: () => rootRouteImport,
} as any)
const DenkToolkitBronnenRoute = DenkToolkitBronnenRouteImport.update({
  id: '/denk/toolkit/bronnen',
  path: '/denk/toolkit/bronnen',
  getParentRoute: () => rootRouteImport,
} as any)
const DenkToolkitLagerpassingenRoute =
  DenkToolkitLagerpassingenRouteImport.update({
    id: '/denk/toolkit/lagerpassingen',
    path: '/denk/toolkit/lagerpassingen',
    getParentRoute: () => rootRouteImport,
  } as any)
const DenkToolkitORinggroefRoute = DenkToolkitORinggroefRouteImport.update({
  id: '/denk/toolkit/o-ringgroef',
  path: '/denk/toolkit/o-ringgroef',
  getParentRoute: () => rootRouteImport,
} as any)
const DenkToolkitPassingenRoute = DenkToolkitPassingenRouteImport.update({
  id: '/denk/toolkit/passingen',
  path: '/denk/toolkit/passingen',
  getParentRoute: () => rootRouteImport,
} as any)
const DenkToolkitSeegerringGroefRoute =
  DenkToolkitSeegerringGroefRouteImport.update({
    id: '/denk/toolkit/seegerring-groef',
    path: '/denk/toolkit/seegerring-groef',
    getParentRoute: () => rootRouteImport,
  } as any)
const DenkToolkitSpiebaanTolerantiesRoute =
  DenkToolkitSpiebaanTolerantiesRouteImport.update({
    id: '/denk/toolkit/spiebaan-toleranties',
    path: '/denk/toolkit/spiebaan-toleranties',
    getParentRoute: () => rootRouteImport,
  } as any)
